import Foundation

/// The UserDefaults keys `AppSettings` owns; `CaseIterable` so the backup harness enumerates them.
enum AppSettingsKey: String, CaseIterable {
    // Every raw value is spelled out so renaming a case can never rename a persisted key.
    case clipboardRetention = "clipboardRetentionDays"
    case clipboardDisabledApps = "clipboardDisabledApps"
    case hyperKey = "hyperKeyPhysicalKey"
    case hyperKeyIncludesShift = "hyperKeyIncludesShift"
    case hyperKeyQuickPress = "hyperKeyQuickPress"
    case emojiSkinTone = "emojiSkinTone"
    case popToRootTimeout = "popToRootTimeout"
    case compactMode = "compactMode"
    case showFavoritesInCompactMode = "showFavoritesInCompactMode"
    case searchScopes = "launcherSearchScopes"
    case openOnCursorScreen = "openOnCursorScreen"
    case autoSwitchInputSource = "autoSwitchInputSource"
    case paletteDraggable = "paletteDraggable"
    case palettePosition = "palettePosition"
    case fileSearchEnabled = "fileSearchEnabled"
    case fileSearchScopes = "fileSearchScopes"
    case fileSearchIgnorePatterns = "fileSearchIgnorePatterns"
    case notesEnabled = "notesEnabled"
    case customCommandsEnabled = "customCommandsEnabled"
    case customCommandsShowInLauncher = "customCommandsShowInLauncher"
    case snippetsEnabled = "snippetsEnabled"
    case snippetsShowInLauncher = "snippetsShowInLauncher"
    case windowManagementEnabled = "windowManagementEnabled"
    case windowManagementShowInLauncher = "windowManagementShowInLauncher"
    case windowGap = "windowManagementGap"
    case windowCycleOnRepeat = "windowManagementCycleOnRepeat"
    case quicklinksEnabled = "quicklinksEnabled"
    case quicklinksShowInLauncher = "quicklinksShowInLauncher"
    case quicklinkOpensNewWindow = "quicklinkOpensNewWindow"
    case quicklinkSelectionFallback = "quicklinkSelectionFallback"
    case quicklinkConfirmsBeforeDelete = "quicklinkConfirmsBeforeDelete"
    case webSearchEnabled = "webSearchEnabled"
    case webSearchShowInLauncher = "webSearchShowInLauncher"
    case webSearchEngine = "webSearchEngine"
    case herdrEnabled = "herdrEnabled"
    case herdrShowInLauncher = "herdrShowInLauncher"
    case herdrTerminalBundleID = "herdrTerminalBundleID"
    case vsCodeEnabled = "vsCodeEnabled"
    case vsCodeShowInLauncher = "vsCodeShowInLauncher"
    case scopeKeywords = "scopeKeywords"
    case linearShowInLauncher = "linearShowInLauncher"
    case linearDestination = "linearDestination"
    case extensionsEnabled = "extensionsEnabled"
    case extensionsShowInLauncher = "extensionsShowInLauncher"
    case extensionPackageManager = "extensionPackageManager"
    case extensionRegistries = "extensionRegistries"
    case extensionCustomSearchPaths = "extensionCustomSearchPaths"
}
